nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
cedula = input("Ingrese su cédula: ")
altura = input("Ingrese su altura en m: ")
peso = input("Ingrese su peso en kg: ")
bmi = input("Ingrese su BMI (Body Mass Index): ")
deporte = input("Ingrese su deporte favorito: ")
promedio = input("Ingrese el promedio de sus calificaciones en su último período estudiantil: ")

print(f"Nombre {nombre}")
print(f"Apellido: {apellido}")
print(f"Cédula: {cedula}")
print(f"Altura: {altura} m ")
print(f"Peso: {peso} kg ")
print(f"BMI (Body Mass Index): {bmi}")
print(f"Deporte favorito: {deporte}")
print(f"Promedio del último período: {promedio} puntos \n")

print(f"El alumno {nombre} {apellido} de C.I. {cedula}, posee una altura de {altura} y un peso: {peso} kg. Su BMI (Body Mass Index) es {bmi}. Su deporte favorito es {deporte}. Y su promedio del último período fue de {promedio} puntos")