datos_personales = {}
nombre = input("Introduzca su nombre completo: ")
datos_personales.update({"Nombre": nombre})
print (datos_personales)
edad = input("Introduzca su edad: ")
datos_personales.update({"Edad": edad})
print (datos_personales)
sexo = input("Introduzca su sexo: ")
datos_personales.update ({"Sexo": sexo})
print (datos_personales)
telf = input("Introduzca su número de teléfono: ")
datos_personales.update ({"Teléfono": telf})
print (datos_personales)
correo = input("Introduzca su correo electrónico: ")
datos_personales.update ({"Correo": correo})
print (datos_personales)