adj1 = input("Please enter 6 adjectives: \n1. ")
adj2 = input("2. ")
adj3 = input("3. ")
adj4 = input("4. ")
adj5 = input("5. ")
adj6 = input("6. ")
plnoun1 = input("Please enter 4 plural nouns: \n1. ")
plnoun2 = input("2. ")
plnoun3 = input("3. ")
plnoun4 = input("4. ")
city = input("Please enter a city: \n ")
place = input("Please enter a place: \n ")
celebrity = input("Please enter a celebrity \n ")
number = input("Please enter a number: \n ")
verb = input("Please enter a verb: \n ")
body1 = input("Please enter 2 body parts: \n1. ")
body2 = input("2. ")
letter = input("Please enter a letter of the alphabet: \n ")
noun1 = input("Please enter 2 singular nouns: \n1. ")
noun2 = input("2. ")
name = input("Please enter a feminine name: \n ")
clothes = input("Please enter a piece of clothing: \n ")

print(f"There are many {adj1} ways to choose a/an {noun1} to read. First, you could ask for recommendations from your friends and {plnoun1}. Just don't ask Aunt {name} -- she only reads {adj2} books with {clothes} -ripping goddesses on the cover. If your friends and family are no help, try checking out the {noun2} Review in 'The {city} Times'. If the {plnoun2} featured there are too {adj3} for your taste, try something a little more low-{body1}, like {letter}: 'The {celebrity} Magazine', or '{plnoun3} Magazine'. You could also choose a book the {adj4}-fashioned way. Head to your local library or {place} and browse the shelves until something catches your {body2}. Or, you could save yourself a whole lot of {adj5} trouble and log on to www.bookish.com, the {adj6} new website to {verb} for books! With all the time you'll save not having to search for {plnoun4}, you can read {number} more books!")